import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { db } from "./firebase";

const SEED_PROS = [
  {
    firstName: "Julien",
    lastName: "Marchand",
    email: "julien.marchand.demo@axe.fr",
    phone: "06 12 34 56 78",
    city: "Paris",
    postalCode: "75011",
    locations: [{ city: "Paris", postalCode: "75011" }],
    homeVisit: true,
    radius: "20",
    profession: "kine",
    specialties: ["post-op", "traumatologie", "genou"],
    experienceYears: 9,
    diploma: "Diplôme d'État de Masseur-Kinésithérapeute (MKDE) — IFMK Paris 2015",
    rppsOrAdeli: "10103456789",
    hasInsurance: true,
    insuranceCompany: "MACSF",
    bio: "Spécialisé en rééducation post-opératoire du genou (LCA, ménisques) et de l'épaule. 9 ans d'expérience en cabinet libéral et suivi de sportifs amateurs à haut niveau. Approche fonctionnelle centrée sur la reprise d'activité.",
    instagram: "@julien.kine.paris",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "certified",
  },
  {
    firstName: "Sophie",
    lastName: "Dufresne",
    email: "sophie.dufresne.demo@axe.fr",
    phone: "06 23 45 67 89",
    city: "Lyon",
    postalCode: "69006",
    locations: [{ city: "Lyon", postalCode: "69006" }, { city: "Villeurbanne", postalCode: "69100" }],
    homeVisit: false,
    radius: "15",
    profession: "osteo",
    specialties: ["récupération", "sport", "tensions cervicales"],
    experienceYears: 7,
    diploma: "Diplôme d'Ostéopathe (D.O.) — ATMAN Lyon 2017 — 5 ans d'études",
    rppsOrAdeli: "79912345678",
    hasInsurance: true,
    insuranceCompany: "Allianz Pro",
    bio: "Ostéopathe spécialisée dans la récupération sportive et la gestion des tensions chroniques. Travail avec des coureurs, cyclistes et nageurs. Consultations sur rendez-vous en cabinet, séances de 45 minutes.",
    instagram: "@sophie.osteo.lyon",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "verified",
  },
  {
    firstName: "Thomas",
    lastName: "Rivière",
    email: "thomas.riviere.demo@axe.fr",
    phone: "06 34 56 78 90",
    city: "Bordeaux",
    postalCode: "33000",
    locations: [{ city: "Bordeaux", postalCode: "33000" }],
    homeVisit: true,
    radius: "30",
    profession: "coach",
    specialties: ["remise en forme", "perte de poids", "reprise sportive"],
    experienceYears: 5,
    diploma: "BPJEPS Activités Physiques pour Tous — CREPS Bordeaux 2019",
    hasInsurance: true,
    insuranceCompany: "Hiscox",
    bio: "Coach sportif certifié BPJEPS. Interventions à domicile et en salle partenaire à Bordeaux. Programmes individualisés 12 semaines pour reprise sportive, perte de poids ou préparation à un trail. Bilan de forme offert à la première séance.",
    website: "https://thomas-riviere-coach.fr",
    status: "approved",
    subscriptionStatus: "free",
    trustLevel: "verified",
  },
  {
    firstName: "Marie",
    lastName: "Besson",
    email: "marie.besson.demo@axe.fr",
    phone: "06 45 67 89 01",
    city: "Marseille",
    postalCode: "13008",
    locations: [{ city: "Marseille", postalCode: "13008" }, { city: "Aix-en-Provence", postalCode: "13100" }],
    homeVisit: false,
    radius: "25",
    profession: "sports_doctor",
    specialties: ["aptitude sportive", "traumatologie", "suivi performance"],
    experienceYears: 14,
    diploma: "Docteur en Médecine — Faculté de Médecine Marseille 2010 — DU Médecine du Sport 2012",
    rppsOrAdeli: "10123456789",
    hasInsurance: true,
    insuranceCompany: "MACSF",
    bio: "Médecin du sport en cabinet libéral. Certificats médicaux d'aptitude, suivi médical de sportifs amateurs et compétiteurs, gestion des blessures et retour à la compétition. Téléconsultation disponible pour les suivis hors urgence.",
    website: "https://dr-besson-medecine-sport.fr",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "elite",
  },
  {
    firstName: "Karim",
    lastName: "Benali",
    email: "karim.benali.demo@axe.fr",
    phone: "06 56 78 90 12",
    city: "Paris",
    postalCode: "75020",
    locations: [{ city: "Paris", postalCode: "75020" }, { city: "Montreuil", postalCode: "93100" }],
    homeVisit: true,
    radius: "15",
    profession: "physical_trainer",
    specialties: ["boxe", "MMA", "préparation combat", "endurance"],
    experienceYears: 8,
    diploma: "DEJEPS Perfectionnement Sportif — Mention Boxe Anglaise — CREPS IDF 2016",
    hasInsurance: true,
    insuranceCompany: "Simplis",
    bio: "Préparateur physique spécialisé sports de combat. Travail avec des boxeurs amateurs et professionnels, artistes martiaux et pratiquants de CrossFit. Cycles périodisés sur 8 à 16 semaines, tests VO2max, analyse vidéo des combats.",
    instagram: "@karim_prep_combat",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "certified",
  },
  {
    firstName: "Lucie",
    lastName: "Fontaine",
    email: "lucie.fontaine.demo@axe.fr",
    phone: "06 67 89 01 23",
    city: "Nantes",
    postalCode: "44000",
    locations: [{ city: "Nantes", postalCode: "44000" }],
    homeVisit: true,
    radius: "20",
    profession: "recovery",
    specialties: ["mobilité", "stretching", "fasciathérapie", "senior"],
    experienceYears: 6,
    diploma: "Licence STAPS Activité Physique Adaptée — Université Nantes 2018 — Formation fasciathérapie MDB",
    hasInsurance: true,
    insuranceCompany: "AXA Pro",
    bio: "Spécialisée en mobilité fonctionnelle et récupération active. Accompagnement de seniors actifs (65-80 ans), sportifs en sur-entraînement et personnes sédentaires reprenant une activité. Séances à domicile ou en studio partenaire à Nantes.",
    status: "approved",
    subscriptionStatus: "free",
    trustLevel: "verified",
  },
  {
    firstName: "Antoine",
    lastName: "Leclerc",
    email: "antoine.leclerc.demo@axe.fr",
    phone: "06 78 90 12 34",
    city: "Toulouse",
    postalCode: "31000",
    locations: [{ city: "Toulouse", postalCode: "31000" }, { city: "Blagnac", postalCode: "31700" }],
    homeVisit: false,
    radius: "20",
    profession: "kine",
    specialties: ["douleur chronique", "lombalgie", "épaule", "rééducation"],
    experienceYears: 11,
    diploma: "Diplôme d'État de Masseur-Kinésithérapeute — IFMK Toulouse 2013",
    rppsOrAdeli: "10456789012",
    hasInsurance: true,
    insuranceCompany: "MACSF",
    bio: "Kinésithérapeute libéral avec 11 ans d'expérience en cabinet. Spécialisé dans la prise en charge des douleurs chroniques (lombalgie, cervicalgie, syndrome de l'épaule). Approche manuelle et rééducation active. Conventionné secteur 1.",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "certified",
  },
  {
    firstName: "Clara",
    lastName: "Morin",
    email: "clara.morin.demo@axe.fr",
    phone: "06 89 01 23 45",
    city: "Lille",
    postalCode: "59000",
    locations: [{ city: "Lille", postalCode: "59000" }, { city: "Roubaix", postalCode: "59100" }],
    homeVisit: true,
    radius: "25",
    profession: "coach",
    specialties: ["performance", "triathlon", "natation", "cyclisme"],
    experienceYears: 7,
    diploma: "Licence STAPS Entraînement Sportif — Université Lille 2017 — Certification Coach Triathlon",
    hasInsurance: true,
    insuranceCompany: "Hiscox",
    bio: "Ancienne triathlète de niveau national reconvertie en coaching. Suivi personnalisé pour triathlètes, cyclistes et nageurs : plans d'entraînement annualisés, analyse des données (power meter, fréquence cardiaque), coaching mental de compétition.",
    instagram: "@clara_coach_tri",
    website: "https://clara-coaching-endurance.fr",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "verified",
  },
  {
    firstName: "Romain",
    lastName: "Garnier",
    email: "romain.garnier.demo@axe.fr",
    phone: "06 90 12 34 56",
    city: "Strasbourg",
    postalCode: "67000",
    locations: [{ city: "Strasbourg", postalCode: "67000" }],
    homeVisit: false,
    radius: "30",
    profession: "osteo",
    specialties: ["post-op", "neuro-méningé", "pédiatrie sportive"],
    experienceYears: 10,
    diploma: "Diplôme d'Ostéopathe — IFSO Strasbourg 2014 — Formation post-graduate approche neuro-méningée",
    rppsOrAdeli: "79856789012",
    hasInsurance: true,
    insuranceCompany: "Allianz Pro",
    bio: "Ostéopathe avec 10 ans de pratique clinique. Approche globale centrée sur les suites opératoires et les restrictions de mobilité complexes. Travail en collaboration avec chirurgiens orthopédiques du CHU de Strasbourg. Prises en charge adultes et adolescents sportifs.",
    status: "approved",
    subscriptionStatus: "premium",
    trustLevel: "elite",
  },
  {
    firstName: "Isabelle",
    lastName: "Perrin",
    email: "isabelle.perrin.demo@axe.fr",
    phone: "07 01 23 45 67",
    city: "Nice",
    postalCode: "06000",
    locations: [{ city: "Nice", postalCode: "06000" }, { city: "Antibes", postalCode: "06600" }],
    homeVisit: true,
    radius: "20",
    profession: "physical_trainer",
    specialties: ["femme enceinte", "post-partum", "bien-être", "gainage"],
    experienceYears: 4,
    diploma: "BPJEPS APT — CREPS PACA 2021 — Formation Prénatal Postpartum Fit",
    hasInsurance: true,
    insuranceCompany: "Simplis",
    bio: "Préparatrice physique spécialisée dans l'accompagnement des femmes enceintes et post-partum. Séances douces adaptées à chaque trimestre, rééducation périnéale de remise en forme après accouchement. Interventions à domicile sur la Côte d'Azur.",
    instagram: "@isabelle_fit_mama",
    status: "approved",
    subscriptionStatus: "free",
    trustLevel: "verified",
  },
];

export async function seedProfessionals(): Promise<number> {
  if (!db) throw new Error("Firebase non configuré");
  let count = 0;
  for (const pro of SEED_PROS) {
    await addDoc(collection(db, "professionals"), {
      ...pro,
      createdAt: serverTimestamp(),
    });
    count++;
  }
  return count;
}
